### ISSUE TITLE
sml_server does not decode testfile from eBZ DD3 2R06

### ISSUE THREAD

**Issue by devZer0** [volkszaehler/libsml#108]
see https://github.com/devZer0/libsml-testing/pull/13

maybe someone likes to debug...

**Comment by r00t-** [comment]
you closed https://github.com/devZer0/libsml-testing/pull/13 , due to the reported data simply being corrupt?
so closing this aswell.

**Comment by r00t-** [comment]
> or if it is different checksum algorithm

note that one such case is already implemented:
https://github.com/volkszaehler/libsml/blob/32910b2fbcd477aedb972e438598b39df9317375/sml/src/sml_message.c#L82
