### ISSUE TITLE
hexdump() compatibility issue with newest Arduino / ESP8266 libraries

### ISSUE THREAD

**Issue by mh-er** [volkszaehler/libsml#113]
There is a name collision of function hexdump() in libSML/sml/src/sml_shared.c and libSML/sml/include/sml_shared.h with the newest Arduino / ESP8266 libraries.

Proposal: rename to sml_hexdump()

**Comment by r00t-** [comment]
https://github.com/volkszaehler/libsml/blob/74e18fccc15bbd881a59befae1f6222f7047921d/sml/src/sml_shared.c#L165

**Comment by r00t-** [comment]
https://github.com/volkszaehler/libsml/blob/74e18fccc15bbd881a59befae1f6222f7047921d/sml/include/sml/sml_shared.h#L110

i wonder if this is part of our public API and if we break any compatibility by removing it?

but a function with such a generic name should not have been exported anyway, and hopefully nobody ever used it.

**Comment by narc-Ontakac2** [comment]
If a version bump is desired - I'll do a release as a basis for a debian package release soon. I'd suggest I'll go to 1.1.0 instead of 1.0.2 and you merge this PR before.

**Comment by mh-er** [comment]
Saw your message just now. I re-based to the latest master. So you could take over the PR.

**Comment by narc-Ontakac2** [comment]
Unfortunately I am the packager. All I do in this project is maintaining the debian packaging. So +1 for me for merging this, but I am not the one to do it.

**Comment by r00t-** [comment]
@narc-Ontakac2:
please do the version bump, i'll merge

**Comment by narc-Ontakac2** [comment]
The merge comes first. I'll then do a release 1.1.0 and from that a Debian release.

**Comment by narc-Ontakac2** [comment]
Since @r00t- decided to merge I did it. Release 1.1.0 will follow.
