### ISSUE TITLE
[sml]  short message from sml_transport_read len=0

### ISSUE THREAD

**Issue by andig** [volkszaehler/libsml#16]
Running at log level 1 I'm getting these messages in the log. Meter is working.

Not sure what the meaning is- should we have a better error message?

**Comment by r00t-** [comment]
note that since https://github.com/volkszaehler/libsml/pull/51 the len=0 case is hanled differently anyway.

**Comment by r00t-** [comment]
@andig:
can you provide feedback, or just close this?

**Comment by andig** [comment]
Closing as can‘t reproduce.
