### ISSUE TITLE
sml_server does not honour EOF when reading STDIN

### ISSUE THREAD

**Issue by devZer0** [volkszaehler/libsml#42]
if you do 

cat binarysml.dump|./sml_server -

the command does never exit.

**Comment by r00t-** [comment]
see also https://github.com/volkszaehler/libsml/issues/32#issuecomment-358830097

**Comment by r00t-** [comment]
fix goes here:
https://github.com/volkszaehler/libsml/blob/master/sml/src/sml_transport.c#L111

**Comment by devZer0** [comment]
did you test that with my binary dumps?  fix does not work for me

**Comment by andig** [comment]
>  fix does not work for me

That's why its work in progress.

**Comment by devZer0** [comment]
i found http://pubs.opengroup.org/onlinepubs/9699919799/functions/read.html

When attempting to read from an empty pipe or FIFO:
    If no process has the pipe open for writing, read() shall return 0 to indicate end-of-file.

and added check like the following (see below).

that works for me, but i'm not sure if it's the correct way to handle that, i'm an awful bad programmer.


size_t sml_read(int fd, fd_set *set, unsigned char *buffer, size_t len) {

        ssize_t r = 0;
        size_t tr = 0;

        while (tr < len) {
                select(fd + 1, set, 0, 0, 0);
                if (FD_ISSET(fd, set)) {
                        r = read(fd, &(buffer[tr]), len - tr);
                        if (r == 0 )break;
                        if (r < 0 ) continue;

                        tr += r;
                }
        }
        return tr;
}

**Comment by andig** [comment]
Fixed by #51
