### ISSUE TITLE
sml_server : add unit conversion from unit.h

### ISSUE THREAD

**Issue by devZer0** [volkszaehler/libsml#44]
what about getting unit.h from vzlogger (https://github.com/volkszaehler/vzlogger/blob/master/include/unit.h )  and include , instead of just statically checking for "W" or "Wh" ? that would be more complete for an universal sml parser binary...

int unitcode = (entry->unit) ? *entry->unit : 0;
char *unit = dlms_get_unit(unitcode);
if ( unit != NULL )
  printf("%s",unit);
else
  printf("n/a");

**Comment by hmueller01** [comment]
Good point. I will look into this.
@andig Is it a problem if I integrate unit.h from vzlogger into examples? Licence should be ok.

**Comment by andig** [comment]
Fine with me.
