### ISSUE TITLE
example server should not use %.1f

### ISSUE THREAD

**Issue by jmberg** [volkszaehler/libsml#58]
The example server is printing all values with %.1f which loses precision if the scaler is less than -1, it should use %.*f instead. I've implemented that here:

https://github.com/jmberg/libsml/commit/31efb5f30eec23bcb33e2588d4cfa3e89a38ae54 ("sml_server: print values with the correct precision")

**Comment by andig** [comment]
Please open a pr

**Comment by jmberg** [comment]
You have a copyright assignment form which I have no intention of signing...

**Comment by andig** [comment]
No problem. Obviously just taking your code won't fix that. Too bad we can't get contributions back in this case. If you want to contribute we'd be happy to welcome you on the developers mailing list to discuss the (inherited) copyright issue.

**Comment by jmberg** [comment]
If you don't actually want the copyright .. I'll make a PR if/when you decide to remove it. FWIW, I've already removed it from my own repository, I'm not even pretending I'd assign any copyright to dailab for things I wrote.
