### ISSUE TITLE
implement DZG meter workaround?

### ISSUE THREAD

**Issue by jmberg** [volkszaehler/libsml#59]
I found that my DZG DVS74 meter has a bug in the encoding of positive values in the range of 327.68..655.36W, it tags them as SIGNED but outputs them as 2 bytes in UNSIGNED format.

I don't know if the library or something else should have a workaround, but I've implemented one in the example server:
https://github.com/jmberg/libsml/commit/456d7e3ee7f36c58bed6468846f42ccd4067960c ("sml_server: implement DZG encoding bug workaround")

**Comment by jmberg** [comment]
will send a PR once the ones I have now are decided upon

**Comment by r00t-** [comment]
@jmberg:
do you have any code for this? (as this issue came up (again) in #125 )

**Comment by jmberg** [comment]
The code is still there, just gated by a model/serial check. I'm travelling now but with the bug data I guess we can extend the workaround.


On 6 July 2023 01:03:44 CEST, "Thorben T." ***@***.***> wrote:
>@jmberg:
>do you have any code for this? (as this issue came up (again) in #125 )
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/volkszaehler/libsml/issues/59#issuecomment-1622649804
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Sent from my phone.
