### ISSUE TITLE
Add note on README.md that this is the active libsml repo

### ISSUE THREAD

**Issue by devZer0** [volkszaehler/libsml#68]
google search for libsml still lists dailab repo as "the only one" and does not give a hint on volkszaehler/libsml  being the correct/active one ( see https://www.google.com/search?q=libsml and http://demo.volkszaehler.org/pipermail/volkszaehler-dev/2015-January/004064.html )

so people could start taking a look at dead code and giving up frustrated

at least this repo should announce some info that it's a fork and that this is the active/maintained project and dailab repo is dead end.

maybe somebody with SEO experience could do something about the position in google search...

also mind: https://github.com/volkszaehler/volkszaehler.org/issues/717

i also mailed debian maintainer, as debian seems to use the old dailab repo

**Comment by andig** [comment]
Why not open a pr instead of an issue?

**Comment by devZer0** [comment]
sorry, i referenced the wrong one...that should have been https://github.com/volkszaehler/libsml/issues/67

**Comment by devZer0** [comment]
this can be closed after merging the pull request
