### ISSUE TITLE
cherrypick 0003-use-nonblock.patch 

### ISSUE THREAD

**Issue by devZer0** [volkszaehler/libsml#73]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=873894

https://salsa.debian.org/amoog-guest/libsml/commit/0ea11cb79cd0bf47a6f6f8f771c561d1e9a6d867

**Comment by Ampelbein** [comment]
That one has already been merged in with https://github.com/volkszaehler/libsml/pull/20
