### ISSUE TITLE
fix gcc-10 build

### ISSUE THREAD

**Issue by r00t-** [volkszaehler/libsml#90]
if this is not fixed, libsml (and dependant packages) won't be in the next debian release.

> Date: Fri, 17 Apr 2020 11:05:01 +0000
> The package fails to build in a test rebuild on at least amd64 with
> gcc-10/g++-10, but succeeds to build with gcc-9/g++-9. The
> severity of this report will be raised before the bullseye release,
> so nothing has to be done for the buster release.

> Severity set to 'serious' from 'normal'  (Wed, 22 Jul 2020 08:05:49 GMT)

-- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=957478

> The next release of Debian is codenamed bullseye — no release date has been set
> Debian 10 (buster) — current stable release

--- https://www.debian.org/releases/

the actual error seems rather trivial,
the tests fail to link due to conflicting variable names (`buf`). i remember reading something about changed variable scoping in object files.

```
make[2]: Leaving directory '/home/r00t/libsml/sml'
cc -I../sml/include/ -std=c99 -Wall -Wextra -pedantic -luuid unity/unity.o unity/unity_fixture.o src/test_helper.o src/sml_octet_string_test.o src/sml_buffer_test.o src/sml_number_test.o src/sml_boolean_test.o src/sml_value_test.o src/sml_status_test.o src/sml_list_test.o src/sml_time_test.o src/sml_tree_test.o src/sml_file_test.o src/sml_open_request_test.o src/sml_get_profile_pack_request_test.o src/sml_message_test.o ../sml/lib/libsml.a test_main.c -o test -luuid
/usr/bin/ld: src/sml_buffer_test.o:(.bss+0x8): multiple definition of `buf'; src/sml_octet_string_test.o:(.bss+0x8): first defined here
/usr/bin/ld: src/sml_number_test.o:(.bss+0x8): multiple definition of `buf'; src/sml_octet_string_test.o:(.bss+0x8): first defined here
/usr/bin/ld: src/sml_boolean_test.o:(.bss+0x8): multiple definition of `buf'; src/sml_octet_string_test.o:(.bss+0x8): first defined here
/usr/bin/ld: src/sml_value_test.o:(.bss+0x8): multiple definition of `buf'; src/sml_octet_string_test.o:(.bss+0x8): first defined here
```

**Comment by devZer0** [comment]
see https://github.com/volkszaehler/libsml/issues/87#issuecomment-751381454

**Comment by devZer0** [comment]
this can be closed.

**Comment by r00t-** [comment]
closing as a duplicate of #87 .
(thought i had done that two days ago)
